#!/usr/bin/env python3
"""
Triết Schema Code Generator

Reads spec/schema/triet-schema.yaml and generates Rust source files.
This is the ONLY way to produce type/AST definitions in the Triết compiler.
Hand-editing the generated files is FORBIDDEN — fix the schema or the
codegen instead.

Usage:
    python3 codegen.py --target rust --schema triet-schema.yaml
    python3 codegen.py --validate triet-schema.yaml
"""

import yaml
import sys
import os
from textwrap import indent, dedent
from datetime import datetime

def make_header():
    import time
    now = datetime.now().isoformat()
    return f"""\
//! AUTO-GENERATED by spec/schema/codegen.py — DO NOT EDIT BY HAND.
//!
//! Generated: {now}Z
//! Source:    spec/schema/triet-schema.yaml
//!
//! To modify: edit the schema, then re-run codegen:
//!   python3 spec/schema/codegen.py --target rust --schema spec/schema/triet-schema.yaml

#![allow(unused_imports, missing_docs)]

"""

RUST_TYPE_MAP = {
    "bool": "bool",
    "string": "String",
    "i8": "i8",
    "i16": "i16",
    "i32": "i32",
    "i64": "i64",
    "i128": "i128",
    "usize": "usize",
    "f64": "f64",
}

# Types that are small (Copy or cheap to move) and should NOT be boxed
# even when they appear as a single field in an enum variant.
SMALL_COPY_TYPES = {
    "TrileanValue",
    "ReferenceForm",
    "BinaryOperator",
    "UnaryOperator",
    "OutcomeArmDiscriminant",
    "Visibility",
    "ParameterPassing",
    "NumericSuffix",
}

# Type prefixes that are already heap-allocated — wrapping in Box is redundant.
HEAP_TYPE_PREFIXES = ("Vec<", "Option<", "String", "Box<")

# Global reference to builtin_types, set during generate_all_rust
_BUILTIN_TYPES = {}

def rust_type(schema_type, owned=True):
    """Map schema type name to Rust type."""
    if schema_type in RUST_TYPE_MAP:
        return RUST_TYPE_MAP[schema_type]

    # Check builtin types first
    if schema_type in _BUILTIN_TYPES:
        return _BUILTIN_TYPES[schema_type]["rust_type"]

    # Handle generic wrappers
    if schema_type.startswith("vector<"):
        inner = schema_type[len("vector<"):-1]
        return f"Vec<{rust_type(inner)}>"
    if schema_type.startswith("option<"):
        inner = schema_type[len("option<"):-1]
        return f"Option<{rust_type(inner)}>"
    if schema_type.startswith("(") and ")" in schema_type:
        # Tuple like "(string, ExprId)"
        parts = schema_type[1:-1].split(",")
        inner_types = [rust_type(p.strip()) for p in parts]
        return f"({', '.join(inner_types)})"

    # Bare reference to another definition
    return schema_type


def needs_box(ftype, enum_name):
    """Return True if ftype should be wrapped in Box<T> to avoid infinite-size recursion.

    A type needs boxing if:
    - It's the same as the enum being defined (direct recursion)
    - It's a known large recursive type

    Types that do NOT need boxing:
    - Already heap-allocated: Vec<T>, Option<T>, String, Box<T>
    - Small Copy types: TrileanValue, ReferenceForm, etc.
    - Scalar primitives: bool, i8-i128, f64
    """
    # Already heap types
    if any(ftype.startswith(prefix) for prefix in HEAP_TYPE_PREFIXES):
        return False
    # Small Copy types that are cheap to move inline
    if ftype in SMALL_COPY_TYPES:
        return False
    # Same-enum recursion ALWAYS needs boxing
    if ftype == enum_name:
        return True
    return False


def field_ownership_comment(field):
    """Generate an ownership annotation comment for a field."""
    ownership = field.get("ownership")
    if ownership == "borrow":
        return " // &0 (borrow)"
    elif ownership == "move":
        return " // owned→move"
    elif ownership == "owned":
        return " // owned"
    return ""


def generate_enum(name, defn, with_serde=True):
    """Generate a Rust enum from a schema enum definition."""
    variants = defn.get("variants", [])
    derive_str = ", ".join(defn.get("derive", ["Clone", "Debug", "PartialEq", "Eq"]))
    lines = []
    status = defn.get("status", "")
    if status == "spec_only":
        lines.append("/// ⚠️ SPEC-ONLY — defined in schema as target specification but NOT yet wired")
        lines.append("/// into the compiler. The typechecker uses a hand-written Type in")
        lines.append("/// `triet-typecheck`. Reconcile is a future phase. Do NOT use this")
        lines.append("/// generated enum in new code until migration is complete.")
        lines.append("///")
    lines.append(f"/// {defn.get('description', name)}")
    lines.append(f"#[derive({derive_str})]")
    if with_serde:
        lines.append(f"#[derive(::serde::Serialize, ::serde::Deserialize)]")
    lines.append(f"pub enum {name} {{")

    for v in variants:
        vname = v["name"]
        vdesc = v.get("description", "")
        fields = v.get("fields", [])
        disc = v.get("discriminant", None)

        doc = f"    /// {vdesc}"
        if disc is not None:
            doc += f" (disc {disc})"
        lines.append(doc)

        if not fields:
            lines.append(f"    {vname},")
        elif len(fields) == 1 and fields[0].get("type") and not isinstance(fields[0]["type"], dict):
            f_type = rust_type(fields[0]["type"])
            f_name = fields[0]["name"]
            own = field_ownership_comment(fields[0])
            if f_type in ("String", "bool", "i8", "i16", "i32", "i64", "i128", "usize", "f64"):
                lines.append(f"    {vname} {{ {f_name}: {f_type} }},{own}")
            elif needs_box(f_type, name):
                lines.append(f"    {vname}(Box<{f_type}>),{own}")
            else:
                lines.append(f"    {vname} {{ {f_name}: {f_type} }},{own}")
        else:
            struct_fields = []
            for f in fields:
                f_type = rust_type(f["type"])
                f_name = f["name"]
                own = field_ownership_comment(f)
                # Box recursive types (field type == the enum we're generating)
                if f_type == name:
                    struct_fields.append(f"        {f_name}: Box<{f_type}>,{own}")
                elif needs_box(f_type, name):
                    struct_fields.append(f"        {f_name}: Box<{f_type}>,{own}")
                else:
                    struct_fields.append(f"        {f_name}: {f_type},{own}")

            lines.append(f"    {vname} {{")
            lines.extend(struct_fields)
            lines.append(f"    }},")

        lines.append("")

    lines.append("}")
    return "\n".join(lines)


def generate_struct(name, defn):
    """Generate a Rust struct from a schema struct definition."""
    fields = defn.get("fields", [])
    derive_str = ", ".join(defn.get("derive", ["Clone", "Debug", "PartialEq", "Eq"]))
    lines = []
    status = defn.get("status", "")
    if status == "spec_only":
        lines.append("/// ⚠️ SPEC-ONLY — defined in schema as target specification but NOT yet wired")
        lines.append("/// into the compiler. Do NOT use this generated struct in new code until")
        lines.append("/// migration is complete.")
        lines.append("///")
    lines.append(f"/// {defn.get('description', name)}")
    lines.append(f"#[derive({derive_str})]")
    lines.append(f"pub struct {name} {{")

    for f in fields:
        f_type = rust_type(f["type"])
        f_name = f["name"]
        f_desc = f.get("description", "")
        own = field_ownership_comment(f)

        lines.append(f"    /// {f_desc}")
        default = f.get("default")
        if default is not None:
            lines.append(f"    pub {f_name}: {f_type},{own} // default: {default}")
        else:
            lines.append(f"    pub {f_name}: {f_type},{own}")

    lines.append("}")
    return "\n".join(lines)


def generate_visitor_trait(name, defn):
    """Generate a visitor trait for an enum."""
    variants = defn.get("variants", [])
    lines = []
    status = defn.get("status", "")
    if status == "spec_only":
        lines.append("/// ⚠️ SPEC-ONLY — see corresponding type annotation above.")
        lines.append("///")
    lines.append(f"/// Visitor for {name} — auto-generated.")
    lines.append(f"pub trait {name}Visitor<R> {{")

    for v in variants:
        vname = v["name"]
        fields = v.get("fields", [])
        if not fields:
            lines.append(f"    fn visit_{snake_case(vname)}(&mut self) -> R;")
        else:
            field_params = []
            for f in fields:
                f_type = rust_type(f["type"])
                field_params.append(f"{f['name']}: &{f_type}")
            params_str = ", ".join(field_params)
            lines.append(f"    fn visit_{snake_case(vname)}(&mut self, {params_str}) -> R;")

    lines.append("}")
    lines.append("")

    # Generate accept method
    lines.append(f"impl {name} {{")
    lines.append(f"    pub fn accept<R>(&self, visitor: &mut impl {name}Visitor<R>) -> R {{")
    lines.append(f"        match self {{")
    for v in variants:
        vname = v["name"]
        fields = v.get("fields", [])
        if not fields:
            lines.append(f"            {name}::{vname} => visitor.visit_{snake_case(vname)}(),")
        else:
            field_names = [f["name"] for f in fields]
            # Detect tuple vs struct variant
            is_tuple = _is_tuple_variant(v, name)
            if is_tuple:
                # Tuple variant: Type::Nullable(inner) → visitor.visit_nullable(inner)
                refs = ", ".join(field_names)
                lines.append(f"            {name}::{vname}({refs}) => visitor.visit_{snake_case(vname)}({refs}),")
            else:
                # Struct variant: Type::BinaryOutcome { value_type, error_type }
                field_refs = ", ".join(field_names)
                lines.append(f"            {name}::{vname} {{ {field_refs} }} => visitor.visit_{snake_case(vname)}({field_refs}),")
    lines.append(f"        }}")
    lines.append(f"    }}")
    lines.append(f"}}")

    return "\n".join(lines)


def _is_tuple_variant(variant, enum_name):
    """Return True if this variant should use tuple-variant syntax (no named fields).

    Tuple variants are used for single-field variants where the field type
    is not a scalar (i.e., it's a large or recursive type wrapped in Box).
    Struct variants are used for multi-field variants or single scalar fields.
    """
    fields = variant.get("fields", [])
    if len(fields) != 1:
        return False
    ftype = rust_type(fields[0]["type"])
    # Scalar types and already-inline types → struct variant with named field
    if ftype in ("String", "bool", "i8", "i16", "i32", "i64", "i128", "usize", "f64"):
        return False
    if any(ftype.startswith(prefix) for prefix in HEAP_TYPE_PREFIXES):
        return False
    if ftype in SMALL_COPY_TYPES:
        return False
    # Box'd recursive types → tuple variant
    if ftype == enum_name or needs_box(ftype, enum_name):
        return True
    # Default to struct variant for clarity
    return False


def snake_case(name):
    """Convert CamelCase to snake_case."""
    result = []
    for c in name:
        if c.isupper() and result:
            result.append("_")
        result.append(c.lower())
    return "".join(result)


def load_schema(path):
    """Load and validate the schema file."""
    with open(path, "r", encoding="utf-8") as f:
        schema = yaml.safe_load(f)
    required_keys = ["schema_version", "definitions"]
    for key in required_keys:
        if key not in schema:
            raise ValueError(f"Schema missing required key: {key}")
    return schema


IMPORT_BLOCK = """\
use crate::arena::{Arena, ExprId, PatternId, StmtId, TypeId};
use crate::span::{Span, Spanned};
use crate::numeric::{NumericSuffix, TrileanValue};
use crate::item::{GenericBound, ImportPath, ImportName};
use triet_core::Integer;
"""

AST_IMPORT_BLOCK = IMPORT_BLOCK + """\
use crate::type_ast::ReferenceForm;
use crate::expr::{FStringPart, FStringSegments, LambdaParam, MatchArm, OutcomeArm};
use super::types::*;
use super::ast_operator::*;
"""

def generate_all_rust(schema, output_dir):
    """Generate all Rust source files from schema."""
    global _BUILTIN_TYPES
    definitions = schema.get("definitions", {})
    builtin_types = schema.get("builtin_types", {})
    _BUILTIN_TYPES = builtin_types.get("types", {})
    codegen_cfg = schema.get("codegen", {})
    rust_cfg = codegen_cfg.get("rust", {})
    with_serde = rust_cfg.get("serde", False)
    os.makedirs(output_dir, exist_ok=True)

    # Filter out section headers and specification-only entries
    code_defs = {k: v for k, v in definitions.items()
                 if not k.startswith("===") and v.get("kind") in ("enum", "struct")}

    # Module index file
    modules = ["types", "ast_operator", "ast_expr", "ast_stmt", "ast_item"]
    mod_lines = [make_header()]
    mod_lines.append("//! Generated modules from triet-schema.yaml\n")
    for m in modules:
        mod_lines.append(f"pub mod {m};")
    # Re-export everything from the top-level generated module
    mod_lines.append(f"pub use types::*;")
    mod_lines.append(f"pub use ast_operator::*;")
    mod_lines.append(f"pub use ast_expr::*;")
    mod_lines.append(f"pub use ast_stmt::*;")
    mod_lines.append(f"pub use ast_item::*;")
    mod_lines.append("")

    with open(os.path.join(output_dir, "mod.rs"), "w") as f:
        f.write("\n".join(mod_lines))

    # Categorize definitions
    type_defs = ["PrimitiveType", "ReferenceForm", "Type", "StructField",
                 "EnumVariant", "Visibility", "ParameterPassing", "TypeParam"]
    operator_defs = ["BinaryOperator", "UnaryOperator"]
    expr_defs = ["Expr", "MatchArm", "LambdaParam"]
    stmt_defs = ["Stmt"]
    item_defs = ["FunctionDef", "FunctionBody", "StructDef", "EnumDef",
                 "Import", "ModuleContent", "ModuleItem", "Item", "Program", "FunctionParam", "ImportName", "ImportPath"]


    # Generate types module
    types_file = [make_header()]
    types_file.append(IMPORT_BLOCK)
    types_file.append("use std::fmt;\n")
    for name in type_defs:
        if name in code_defs:
            d = code_defs[name]
            if d["kind"] == "enum":
                types_file.append(generate_enum(name, d, with_serde))
            elif d["kind"] == "struct":
                types_file.append(generate_struct(name, d))
            types_file.append("")
        else:
            types_file.append(f"// {name}: defined in schema but skipped (kind={definitions.get(name, {}).get('kind', 'N/A')})")
            types_file.append("")

    # Generate visitor trait for Type
    if "Type" in code_defs:
        types_file.append(generate_visitor_trait("Type", code_defs["Type"]))
        types_file.append("")

    with open(os.path.join(output_dir, "types.rs"), "w") as f:
        f.write("\n".join(types_file))

    # Generate AST operator module
    op_file = [make_header()]
    op_file.append("use std::fmt;\n")
    for name in operator_defs:
        if name in code_defs:
            d = code_defs[name]
            if d["kind"] == "enum":
                op_file.append(generate_enum(name, d, with_serde))
            elif d["kind"] == "struct":
                op_file.append(generate_struct(name, d))
            op_file.append("")
    with open(os.path.join(output_dir, "ast_operator.rs"), "w") as f:
        f.write("\n".join(op_file))

    # Generate AST expression module
    expr_file = [make_header()]
    expr_file.append(AST_IMPORT_BLOCK)
    for name in expr_defs:
        if name in code_defs:
            d = code_defs[name]
            if d["kind"] == "enum":
                expr_file.append(generate_enum(name, d, with_serde))
            elif d["kind"] == "struct":
                expr_file.append(generate_struct(name, d))
            expr_file.append("")
    with open(os.path.join(output_dir, "ast_expr.rs"), "w") as f:
        f.write("\n".join(expr_file))

    # Generate AST statement module
    stmt_file = [make_header()]
    stmt_file.append(AST_IMPORT_BLOCK)
    stmt_file.append("use super::ast_expr::*;\n")
    for name in stmt_defs:
        if name in code_defs:
            d = code_defs[name]
            if d["kind"] == "enum":
                stmt_file.append(generate_enum(name, d, with_serde))
            elif d["kind"] == "struct":
                stmt_file.append(generate_struct(name, d))
            stmt_file.append("")
    with open(os.path.join(output_dir, "ast_stmt.rs"), "w") as f:
        f.write("\n".join(stmt_file))

    # Generate AST item module
    item_file = [make_header()]
    item_file.append(AST_IMPORT_BLOCK)
    item_file.append("use super::ast_expr::*;")
    item_file.append("use super::ast_stmt::*;\n")
    for name in item_defs:
        if name in code_defs:
            d = code_defs[name]
            if d["kind"] == "enum":
                item_file.append(generate_enum(name, d, with_serde))
            elif d["kind"] == "struct":
                item_file.append(generate_struct(name, d))
            item_file.append("")
    with open(os.path.join(output_dir, "ast_item.rs"), "w") as f:
        f.write("\n".join(item_file))

    return output_dir


def validate_schema(schema):
    """Validate the schema for completeness and consistency."""
    errors = []
    definitions = schema.get("definitions", {})
    builtin_types = set(schema.get("builtin_types", {}).get("types", {}).keys())

    # Known scalar types that don't need ownership annotations
    scalar_types = {"bool", "string", "i8", "i16", "i32", "i64", "i128", "usize", "f64"}

    def resolve_base_type(ftype):
        """Extract base type name from generic wrappers."""
        base = ftype
        # Strip generic wrappers outermost-first. `Spanned<` is a builtin
        # wrapper (crate::span::Spanned<T>) and may nest inside vector<…>.
        for wrapper in ["vector<", "option<", "Spanned<"]:
            if base.startswith(wrapper):
                base = base[len(wrapper):-1]
        # Handle tuples
        if base.startswith("("):
            return None  # tuples are inline, can't validate
        return base

    # Check that all referenced types exist
    for name, defn in definitions.items():
        if name.startswith("==="):
            continue
        if defn.get("kind") in ("enum", "struct"):
            variants = defn.get("variants", [])
            fields = defn.get("fields", [])
            all_fields = list(fields)
            for v in variants:
                all_fields.extend(v.get("fields", []))

            for f in all_fields:
                ftype = f.get("type", "")
                base = resolve_base_type(ftype)
                if base is None:
                    continue
                # Skip builtin types, scalars, and self-references
                if base in builtin_types or base in scalar_types or base == name:
                    continue
                if base not in RUST_TYPE_MAP and base not in definitions:
                    errors.append(
                        f"{name}.{f.get('name', '?')}: "
                        f"type '{ftype}' (base: '{base}') not found in schema or builtin_types"
                    )

    # Check ownership annotations
    for name, defn in definitions.items():
        if name.startswith("===") or defn.get("kind") != "enum":
            continue
        for v in defn.get("variants", []):
            for f in v.get("fields", []):
                ftype = f.get("type", "")
                base = resolve_base_type(ftype)
                if base is None:
                    continue
                if f.get("ownership"):
                    continue
                if base in scalar_types or base in builtin_types:
                    continue
                # ownership annotation recommended but not required for references
                # within the same definition set

    return errors


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    args = sys.argv[1:]
    target = "rust"
    schema_path = "spec/schema/triet-schema.yaml"
    output_dir = "crates/triet-syntax/src/generated"

    i = 0
    while i < len(args):
        if args[i] == "--target" and i + 1 < len(args):
            target = args[i + 1]
            i += 2
        elif args[i] == "--schema" and i + 1 < len(args):
            schema_path = args[i + 1]
            i += 2
        elif args[i] == "--out" and i + 1 < len(args):
            output_dir = args[i + 1]
            i += 2
        elif args[i] == "--validate":
            target = "validate"
            i += 1
            if i < len(args) and not args[i].startswith("--"):
                schema_path = args[i]
                i += 1
        else:
            print(f"Unknown argument: {args[i]}")
            sys.exit(1)

    if target is None:
        print("Error: --target required (rust | triet | validate)")
        sys.exit(1)

    schema = load_schema(schema_path)

    if target == "validate":
        errors = validate_schema(schema)
        if errors:
            print(f"Schema validation FAILED — {len(errors)} errors:")
            for e in errors:
                print(f"  ✗ {e}")
            sys.exit(1)
        else:
            print("Schema validation PASSED ✓")
            return

    if target == "rust":
        out = generate_all_rust(schema, output_dir)
        print(f"Generated Rust sources → {out}/")
        print(f"  ├── mod.rs")
        print(f"  ├── types.rs        (Type, ReferenceForm, ...)")
        print(f"  ├── ast_expr.rs     (Expr, operators)")
        print(f"  ├── ast_stmt.rs     (Stmt)")
        print(f"  └── ast_item.rs     (Item, Program)")
        return

    if target == "triet":
        print("Triết codegen target not yet implemented — deferred to language v1.0")
        print("When ready, this will generate compiler/generated/*.tri from the same schema.")
        return

    print(f"Unknown target: {target}")


if __name__ == "__main__":
    main()
